api.py:25 - 2025-01-28 19:59:22,112 - ERROR - Error : 400: Only CSV files are allowed.
api.py:25 - 2025-01-28 19:59:22,112 - ERROR - Error : 400: Only CSV files are allowed.
api.py:25 - 2025-01-28 19:59:22,112 - ERROR - Error : 400: Only CSV files are allowed.
service.py:47 - 2025-01-28 20:00:07,380 - INFO - Save file : {'row_count': 79, 'column_count': 15, 'empty_cells': 4, 'file_name': 'metadata 2.csv', 'id': '38adb077-ce99-4e50-9bfb-adcf4cd63ee9', 'uploaded_at': datetime.datetime(2025, 1, 28, 20, 0, 7, 285533)}
service.py:47 - 2025-01-28 20:00:07,380 - INFO - Save file : {'row_count': 79, 'column_count': 15, 'empty_cells': 4, 'file_name': 'metadata 2.csv', 'id': '38adb077-ce99-4e50-9bfb-adcf4cd63ee9', 'uploaded_at': datetime.datetime(2025, 1, 28, 20, 0, 7, 285533)}
service.py:47 - 2025-01-28 20:00:07,380 - INFO - Save file : {'row_count': 79, 'column_count': 15, 'empty_cells': 4, 'file_name': 'metadata 2.csv', 'id': '38adb077-ce99-4e50-9bfb-adcf4cd63ee9', 'uploaded_at': datetime.datetime(2025, 1, 28, 20, 0, 7, 285533)}
api.py:22 - 2025-01-28 20:00:07,380 - INFO - File uploaded successfully metadata 2.csv
api.py:22 - 2025-01-28 20:00:07,380 - INFO - File uploaded successfully metadata 2.csv
api.py:22 - 2025-01-28 20:00:07,380 - INFO - File uploaded successfully metadata 2.csv
dao.py:29 - 2025-02-02 10:11:59,138 - ERROR - (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
dao.py:29 - 2025-02-02 10:11:59,138 - ERROR - (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
dao.py:29 - 2025-02-02 10:11:59,138 - ERROR - (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
service.py:50 - 2025-02-02 10:11:59,141 - ERROR - Error : Error uploading file: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
service.py:50 - 2025-02-02 10:11:59,141 - ERROR - Error : Error uploading file: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
service.py:50 - 2025-02-02 10:11:59,141 - ERROR - Error : Error uploading file: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
api.py:25 - 2025-02-02 10:11:59,141 - ERROR - Error : Error uploading CSV file: Error uploading file: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
api.py:25 - 2025-02-02 10:11:59,141 - ERROR - Error : Error uploading CSV file: Error uploading file: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
api.py:25 - 2025-02-02 10:11:59,141 - ERROR - Error : Error uploading CSV file: Error uploading file: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
